DROP TABLE T_PATIENT IF EXISTS;
DROP TABLE T_ROOM IF EXISTS;

CREATE TABLE T_PATIENT (ID INTEGER IDENTITY PRIMARY KEY, NAME VARCHAR(50) not null, LASTNAME VARCHAR(100) NOT NULL, ROOMID INTEGER);
CREATE TABLE T_ROOM (ID INTEGER IDENTITY PRIMARY KEY, MAXPATIENTS INTEGER);


