INSERT INTO T_ROOM (ID, MAXPATIENTS) VALUES (1, 2);
INSERT INTO T_ROOM (ID, MAXPATIENTS) VALUES (2, 3);

INSERT INTO T_PATIENT(ID, NAME, LASTNAME, ROOMID) VALUES (1,'Marshall', 'Zieman',1);
INSERT INTO T_PATIENT(ID, NAME, LASTNAME, ROOMID) VALUES (2,'Russ', 'Dunham',1);
INSERT INTO T_PATIENT(ID, NAME, LASTNAME, ROOMID) VALUES (3,'Sarah', 'Tutino',2);


