INSERT INTO T_ROOM (ID, MAXPATIENTS) VALUES (1, 2);
INSERT INTO T_ROOM (ID, MAXPATIENTS) VALUES (2, 3);

INSERT INTO T_PATIENT(ID, NAME, LASTNAME, ROOMID) VALUES (1,'John', 'Doe',1);
INSERT INTO T_PATIENT(ID, NAME, LASTNAME, ROOMID) VALUES (2,'Juan', 'Nadie',1);
INSERT INTO T_PATIENT(ID, NAME, LASTNAME, ROOMID) VALUES (3,'Forever', 'Alone',2);


